### ISSUE TITLE
Script failed to complete due to subprocess error...

### ISSUE THREAD

**Issue by vaquierm** [mcgill-robotics/compsys#102] opened 2017-10-14 14:48 UTC
The .tmuxinator directory has to be created manually to complete the script. Several other people ran into this issue trying to install ROS.
![ros_installation error](https://user-images.githubusercontent.com/25057940/31576642-12ac279e-b0cd-11e7-8afa-f7c5a62923f0.png)

**Comment by foochuanwei** [comment] 2017-10-14 20:39
The problem is likely caused by having spaces in your path.
Try: `mv ~/Desktop/"McGill Robotics"/ ~/Desktop/mcgill-robotics/` and then rerun install.
I'll look into this.

**Comment by anassinator** [comment] 2017-10-14 21:10
This is a `rover` issue. Needs to be fixed in the `rover` repo's `setup.sh`.

**Closed by anassinator** 2017-10-14 21:10 UTC
